### PR TITLE
fixing yes no

### PR DESCRIPTION
**Pull request by emirchus**
Now the buttons has a timings

### CODE REVIEW

**Comment by Da-PC** [comment]
Hello hello @emirchus still happening as the state is not changing fast enough. 
[si nop.webm](https://user-images.githubusercontent.com/127154933/232081687-215a2a86-4061-453a-a02c-b868609f5f92.webm)

**Comment by hectoritr** [comment]
Hey, I've just tested it. Still happening.

**Comment by hectoritr** [comment]
@emirchus This has conflicts I can't solve. Please fix them and push again

**Comment by emirchus** [comment]
@hectoritr merge conflicts solved.

**Comment by Da-PC** [comment]
@emirchus Still not working

[si no segundo error.webm](https://github.com/OTTAA-Project/ottaa_project_flutter/assets/127154933/109e6755-f794-4f86-b0cf-6b2c2dd0b449)

**Pull request merged**
